### ISSUE TITLE
USB SSD compatibility on 3B/4

### ISSUE THREAD

**Issue by Cjkeenan** [FrangaL/rpi-img-builder#1]
The work you have put in looks great so far but I have a couple of questions.

1. Does this only work on Linux or is there a way to generate an image from Windows?
2. Does it generate an image that works with the Official Raspberry Pi Imager or is the flashing method provided in the README the only way?
3. Do you know where I can find a list of valid LOCALES and TIMEZONES?
4. What is the difference between lite and slim variants?
5. What are some of the reasons why I would want to change the boot partition size?
6. What is the use of the proxy URL and if I set one will it affect any webservers that are being hosted on the pi?

Again thank you so much, I have been trying to find a way to get F2FS working on a RPi, and when I tried manually converting I had a lot of issues that eventually resulted in a GCC compiler corruption, so now I am starting from scratch.

**HW Info:**
- Raspberry Pi 3 Model B v1.2 (4 Model B in the mail)
- Western Digital Blue SATA SSD 250GB with ASM1153e based USB adapter
- Plan to host Network UPS Tools server, Node-RED instance, Pi-Hole, PiVPN, potentially Home Assistant

**Comment by FrangaL** [comment]
1. You can create the images from windows using Docker.
Template Docker https://github.com/FrangaL/images-builder
You have pre-compiled images in https://rpi-images.site/

  Only change time zone and locale
  execute
```bash
dpkg-reconfigure locales
```
   Edit /etc/locale.conf
execute
```bash
source /etc/locale.conf
export LANG

dpkg-reconfigure tzdata
```

2. Surely compatible with the sea, I recommend https://www.balena.io/etcher/

3. Time zone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

4. Slim version purge locales,docs and exclude install Raspberry Pi Videocore https://github.com/raspberrypi/userland

5. Maybe you think it is too big or small to store different kernel versions.

6. The use of the proxy does not affect the image, it only speeds up the installation if you have to compile many images, it requires having apt-cacher-ng installed.

F2FS is still experimental in the script, I don't guarantee it will work correctly yet.
