### ISSUE TITLE
DietPi support

### ISSUE THREAD

**Issue by Cjkeenan** [FrangaL/rpi-img-builder#4]
Would it be possible to add DietPi (https://github.com/MichaIng/DietPi) as another OS option for the builder? I have been using it recently and loving the fact that it is lighter than Raspbian OS Lite and IMO more well featured including software browser, backup options, and a whole host of other features.

**Comment by FrangaL** [comment]
I don't think I'm going to integrate Dietpi, that's what Dietpi is for, the idea of ​​my script is a cleaner system without script, there are other priorities like integrating Ubunu and Kali
